#!/bin/sh


DEPOT_TOOLS="depot_tools"
SHOW_HELP_MENU=
VERSION="1.0.3"
GET_DEPOT_TOOL=
CURRENT_LOCATION=$(pwd)
export PATH=$PATH:/$(pwd)/depot_tools


help_menu () {
    echo "Usage: crosenv [repo command=n] [code source=n]"
    echo "Commands:"
    echo "  v : crosenv version"
    echo "  i : repo init [firmware branch]"
    echo "  s : repo sync"
    echo "  c : cros_sdk"
    echo "  d : cros_sdk --delete"
    echo "  r : cros_sdk --replace"
    echo "  h : help"
}

get_depot_tool () {
    read -p "depot_tool is not exsit, press 'y' for download depot tool: " answer
    if test "$answer" = "y" || test "$answer" = "Y" 
    then
        echo "download now..."
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    fi
}

crosenv_version() {
	echo "crosenv version ${VERSION}"
}

repo_init() {
    echo "------> repo init"
}

repo_sync() {
    echo "------> repo sync"
    repo sync
}

cros_del() {
    echo "------> cros delete"
    cros_sdk --delete
}

cros_replace() {
    echo "------> cros replace"
    cros_sdk --replace
}
crossdk(){
    echo "------> cros_sdk"
    cros_sdk --no-ns-pid
}

###########################################################
main() {
    
    local GET_DEPOT_TOOL="FLASE"
    local brach_name=

    if [ ! -d $(pwd)/depot_tools ]; then
        get_depot_tool
    fi
 
    while getopts 'vhi:scdr' flag; do
    case ${flag} in
      h) help_menu ;;
      v) crosenv_version ;;
      i) brach_name="OPTARG" repo_init brach_name ;;
      s) repo_sync ;; 
      c) cros_sdk ;;
      d) cros_del ;;
      r) cros_replace ;;
      *) die "invalid option found" ;;
    esac
  done

}
main "$@"
