#!/bin/sh

# Text STYLE variables
BOLD="\033[1m"
RED='\033[38;5;9m'
GREEN='\033[38;5;2m'
ORANGE_RED="\033[38;5;202m"
C_DODGERBLUE2="\033[38;5;27m"

VERSION='flashCB  v0.0.1'

die() {
  echo "${0##*/}: error: $*" >&2
  exit 1
}

_echo_color() {
	printf "${1}%s${NC}\n" "$2"
}
_printf_color() {
	printf "${1}%s" "$2"
	_echo_color "${NC}" ""
}

usage() {
  echo "Usage: flash_cb [board] [type] 

  This does something useful!

  Options:
    -v          show version 
    -h          help"
  exit 0
}

flash_image (){

    _printf_color "${BOLD}" "------> flash start"
    echo "flash" $1 with $2

}

###############################################################################
#
#
#
main () {
    local board=""
    local type=""

    while getopts 'vhb:t:' flag; do

    case ${flag} in
      v) echo "${VERSION}" ;;  
      h) usage ;;
      b) board="${OPTARG}" ;;
      t) type="${OPTARG}" ;;
      *) die "invalid option found" ;;
    esac
    done
   
    if [ -z $board ] || [ -z $type ]; then
        usage
    else
        flash_image ${board} ${type}
    fi
}

main "$@"
