#!/bin/bash
VERSION='1.0.0'
SHOW_HELP_MENU=

die() {
  echo "${0##*/}: error: $*" >&2
  exit 1
}

flash_cb_version() {
  echo "flash coreboot version ${VERSION}"
}
usage() {
  echo "Usage: flash_cb [board] [type] 

  This does something useful!

  Options:
    -v          show version 
    -h          help"
  exit 0
}

get_board(){
    echo $2
    exit 0
}

get_type(){
    echo $2
    exit 0
}
###############################################################################
#
#
#
args=$(getopt -l version,help,board,type -o vhb:t: -- "$@")
getopt_ret=$?
eval set -- "${args}"

if [ ${getopt_ret} != 0 ]; then
    SHOW_HELP_MENU=1
fi
 
while true ; do
    case "$1" in
      -v|--version)		shift; flash_cb_version; exit 0;;
      -h|--help)		    shift; SHOW_HELP_MENU=1;;
      -b|--board)		    shift; get_board;;
      -t|--type)		    shift; get_type;;
        --)			        shift; break;; 
  esac
  done

if [ "${SHOW_HELP_MENU}" ]; then
  usage
  exit 0
fi
