global_timeout: 600
logging:
  backup_count: 5
  file_path: postcodemon.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json_format: false
  level: INFO
  max_file_size: 10485760
  remote_endpoint: null
max_concurrent_jobs: 10
metrics_endpoint: null
monitoring_enabled: true
profiles:
  development:
    global_timeout: 1200
    logging:
      level: DEBUG
  production:
    global_timeout: 300
    logging:
      level: WARNING
temp_directory: null
tools:
  PostCodeMon:
    default_args:
    - "10.98.35.153"  
    - "kysy"
    - "kysy"
    environment_vars:
      TOOL_HOME: C:\Users\chri\Firmware-Dev\tool\PostCodeMon\monitor_postcode_KYSY4
      TOOL_LOG_LEVEL: INFO
    executable_path: C:\Users\chri\Firmware-Dev\tool_script\py\PostCodeMon\monitor_postcode_KYSY4\monitor_postcode_KYSY4.exe
    working_directory: C:\Users\chri\Firmware-Dev\tool_script\py\PostCodeMon\monitor_postcode_KYSY4
    retry_attempts: 1000
    retry_wait_seconds: 10
    timeout_seconds: 300
    validation_rules: {}
